### ISSUE TITLE
 getCurrentWeatherByGeoCoordinates returns Forecast

### ISSUE THREAD

**Issue by JohannesHoffmann** [Raqhael/openweathermap-ts#10]
the method  getCurrentWeatherByGeoCoordinates returning the forecast instead of the current weather.

The reason for this is that FORECAST is set instead of WEATHER in 

https://github.com/shimphillip/openweathermap-ts/blob/1f7cf72b3b01c61762c4669a73f56837c7e76d97/src/app.ts#L52

**Comment by ghost** [comment]
Thanks @JohannesHoffmann @Looskie This issue is closed

**Comment by looskie** [comment]
> Thanks @JohannesHoffmann @Looskie This issue is closed

you're fantastic thank you so much ❤️
